### ISSUE TITLE
Create Friend routes for the mock api + doc

### ISSUE THREAD

**Issue by TimV22** [Inholland-Hydroguard/mock-api#5]
The openAPI spec can be found [here](https://inholland-my.sharepoint.com/:u:/r/personal/668419_student_inholland_nl/Documents/Cloud-project-hydroguard/OpenAPI/Microservices/Open-API-Huishouden-Friends.yaml?csf=1&web=1&e=ommwva)

**This document is not perfect and still needs some changes, so make sure it is up-to-date and consistent with others**

**Comment by FlorisBeentjes** [comment]
Documentation not edited since @TimV22 added Swagger
